function trackers = configTrackers_ifs()

trackers = {
%         struct('name','Staple','namePaper','Staple')
%         struct('name','DSST'  ,'namePaper','DSST')
%         struct('name','SRDCF'  ,'namePaper','SRDCF')
%         struct('name','KCF'  ,'namePaper','KCF')
%         struct('name','fDSST'  ,'namePaper','fDSST')
%         struct('name','Staple_CA'  ,'namePaper','Staple_CA')
%         struct('name','BACF'  ,'namePaper','BACF')
%         struct('name','STRCF'  ,'namePaper','STRCF')
%         struct('name','LCT'  ,'namePaper','LCT')
%         struct('name','CSRDCF'  ,'namePaper','CSRDCF')
%         struct('name','HCFT'  ,'namePaper','HCFT')
%         struct('name','ECO'  ,'namePaper','ECO')
%         struct('name','SCT'  ,'namePaper','SCT')
%         struct('name','DSiam'  ,'namePaper','DSiam')
%         struct('name','TRACA'  ,'namePaper','TRACA')
%         struct('name','PTAV'  ,'namePaper','PTAV')
%         struct('name','CFNet'  ,'namePaper','CFNet')
%         struct('name','SiameseFC'  ,'namePaper','SiameseFC')
%         struct('name','SiamRPN++'  ,'namePaper','SiamRPN++')
%         struct('name','GFSDCF'  ,'namePaper','GFSDCF')
%         struct('name','ARCF'  ,'namePaper','ARCF')
%         struct('name','ASRCF'  ,'namePaper','ASRCF')
%         struct('name','AutoTrack'  ,'namePaper','AutoTrack')
%         struct('name','SiamBAN'  ,'namePaper','SiamBAN')
%         struct('name','SiamDW'  ,'namePaper','SiamDW')
%         struct('name','ocean'  ,'namePaper','Ocean')

%         struct('name','DSiam'  ,'namePaper','DSiam')
%         struct('name','DSiam_VAF'  ,'namePaper','DSiam_VAF')
%         struct('name','DSiam_RD'  ,'namePaper','DSiam_RD')
%         struct('name','DSiam_RD_VAF'  ,'namePaper','DSiam_RD_VAF')
%         struct('name','DSiam_TS'  ,'namePaper','DSiam_TS')
%         struct('name','DSiam_TS_VAF'  ,'namePaper','DSiam_TS_VAF')
%         struct('name','DSiam_RD_TS'  ,'namePaper','DSiam_RD_TS')
        struct('name','ASNet'  ,'namePaper','ASNet(AFS)')
    };
