function net = reshapeNet_vgg(net,opts,sumw_lr)
nettype = opts.nettype;

xcorrout = {'xcorr_out'};
if strcmp(nettype,'1res')
   xcorrout = {'xcorr0_out'}; 
end

% add target variation transformation for a_feat
net.addLayer('circonv1_1',...
    CirConv('isrep',true),opts.netconv_input{1},{'ta_feat'},...
    {'cir11_alphaf','cir11_featf','cir11_lr','v_enable'});

% add background suppression transformation for b_feat
net.addLayer('circonv1_2',...
    CirConv(),opts.feat_name{1},{'tb_feat'},...
    {'cir12_alphaf','cir12_featf','cir12_lr','w_enable'});

net.addLayer('xcorr0',...
        XCorr(),...
        {'ta_feat','tb_feat'},...
        xcorrout,...
        {});
net.params(net.getParamIndex('cir11_lr')).value = opts.vlr;
net.params(net.getParamIndex('cir12_lr')).value = opts.wlr;

if strcmp(nettype,'1res')
    
    % add target variation transformation for a_feat
    net.addLayer('circonv2_1',...
        CirConv('isrep',true),opts.netconv_input{2},{'ta_feat1'},...
        {'cir21_alphaf','cir21_featf','cir21_lr','v_enable'});
    
    % add background suppression transformation for b_feat
    net.addLayer('circonv2_2',...
        CirConv(),opts.feat_name{2},{'tb_feat1'},...
        {'cir22_alphaf','cir22_featf','cir22_lr','w_enable'});
    
    net.addLayer('xcorr1',...
        XCorr(),...
        {'ta_feat1','tb_feat1'},...
        {'xcorr1_out'},...
        {});
    
    net.params(net.getParamIndex('cir21_lr')).value = opts.vlr;
    net.params(net.getParamIndex('cir22_lr')).value = opts.wlr;
    
    net.addLayer('sumw',Sum_w(),{'xcorr0_out','xcorr1_out'},...
        {'xcorr_out'},{'sumweights'});
    net.params(net.getParamIndex('sumweights')).value = sumw_lr.*ones(opts.scoreSize,opts.scoreSize,'single');
end

add_adjust_layer(net, 'adjust', 'xcorr_out', 'score', ...
                 {'adjust_f', 'adjust_b'}, 1e-8, 0, 0, 1);
net.rebuild();
